### ISSUE TITLE
Clarifying settings in control files

### ISSUE THREAD

**Issue by darencard** [lliu1871/begfe#2]
I am hoping that some description of the control files can be provided so I can understand how to run the program on my own data. In looking at the files, I can reasonably guess certain fields, but there are others where I am puzzled. Apologies if I missed this information somewhere, but I have looked through the repo and cannot find any explanations.

controlsim
```
1
sim1
-1
124
5
(((chimp:6,human:6):81,(mouse:17,rat:17):70):6,dog:93);
5 15
0.005 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001 0.001
```

control1
```
0
sim1
-1
122
5
(((chimp:6,human:6):81,(mouse:17,rat:17):70):6,dog:93);
10000 100 0
```

Thanks in advance for the help.
Daren Card

**Comment by lliu1871** [comment]
I have updated the source code and README.md by adding explanations for the control files.

Liang

Graduate coordinator
Department of Statistics
Institute of Bioinformatics
University of Georgia
Phylogenetics Lab | Phylogenetics Lab (uga.edu)<http://faculty.franklin.uga.edu/lliu/>
[cid:image001.png@01D6C88D.F9A348A0]

**Comment by darencard** [comment]
Thank you, Liang - that should give me what I need to start up a run! Will reach out if any other questions come up.
